apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-metrics-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-metrics
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: mini-metrics
        tier: backend
        track: stable
    spec:
      containers:
        - name: mini-metrics
          image: mini-metrics-backend-image
          imagePullPolicy: Never
          resources:
            # requests:
            #   memory: "64Mi"
            #   cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "125m"
          ports:
          - containerPort: 5000
